# Generated by Django 5.1.2 on 2024-10-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='role',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', 'Admin')], max_length=10),
        ),
    ]
