# Generated by Django 5.1.2 on 2025-01-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usersmodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер Телефона'),
        ),
    ]
