# Generated by Django 5.1.2 on 2025-03-27 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usersmodel_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAdminActionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_flag', models.IntegerField(choices=[(0, 'Создать'), (1, 'Изменить'), (2, 'Удалить')], default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
