# Generated by Django 5.1.2 on 2025-03-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_logadminactionsmodel_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='logadminactionsmodel',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
