# Generated by Django 5.1.2 on 2025-03-27 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_logadminactionsmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='logadminactionsmodel',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
