# Generated by Django 5.1.2 on 2025-03-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_logadminactionsmodel_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logadminactionsmodel',
            old_name='action_flag',
            new_name='flag',
        ),
    ]
