# Generated by Django 5.1.2 on 2025-03-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_logadminactionsmodel_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logadminactionsmodel',
            name='flag',
            field=models.CharField(choices=[('0', 'Создать'), ('1', 'Изменить'), ('2', 'Удалить')], default=0, max_length=10),
        ),
    ]
