# Generated by Django 5.1.2 on 2025-03-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_logadminactionsmodel_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logadminactionsmodel',
            name='flag',
        ),
        migrations.AddField(
            model_name='logadminactionsmodel',
            name='action_number',
            field=models.CharField(choices=[('0', 'Создать'), ('1', 'Изменить'), ('2', 'Удалить')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
