# Generated by Django 5.1.2 on 2025-03-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_logadminactionsmodel_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logadminactionsmodel',
            name='action_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Addition'), (2, 'Change'), (3, 'Deletion')]),
        ),
    ]
