# Generated by Django 5.1.2 on 2025-03-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_logadminactionsmodel_action_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logadminactionsmodel',
            name='action_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Создать'), (2, 'Изменить'), (3, 'Удалить')]),
        ),
    ]
