# Generated by Django 5.1.2 on 2025-04-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_logadminactionsmodel_action_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='role',
            field=models.CharField(choices=[('1', 'Учитель'), ('2', 'Администратор')], default='1', max_length=10, verbose_name='Роль'),
        ),
    ]
