# Generated by Django 5.1.2 on 2025-04-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_usersmodel_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logadminactionsmodel',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
        migrations.AlterModelOptions(
            name='usersmodel',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
