# Generated by Django 5.1.2 on 2025-03-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_logadminactionsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True),
        ),
    ]
