# Generated by Django 5.1.2 on 2025-03-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_usersmodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, null=True, verbose_name='Цвет выделения'),
        ),
    ]
