# Generated by Django 5.1.2 on 2025-08-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_usersmodel_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chat_id', models.CharField(max_length=100)),
            ],
        ),
    ]
