# Generated by Django 5.1.2 on 2025-08-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_telegramchatsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='custom_permissions',
            field=models.CharField(choices=[('view', 'Can View'), ('edit', 'Can Edit'), ('approve', 'Can Approve'), ('delete', 'Can Delete')], default='view', max_length=50),
        ),
    ]
