# Generated by Django 5.1.2 on 2025-08-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_usersmodel_custom_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='custom_permissions',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
