# Generated by Django 5.1.2 on 2025-08-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_usersmodel_custom_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=['delete_enrollment', 're_enrollment', 'mark_session', 'change_attendance', 'create_payment'], null=True),
        ),
    ]
