# Generated by Django 5.1.2 on 2025-09-20 10:01

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_usersmodel_custom_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.convert_file_name),
        ),
    ]
