# Generated by Django 5.1.2 on 2025-09-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_usersmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
