# Generated by Django 5.1.2 on 2025-09-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_usersmodel_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
    ]
