# Generated by Django 5.1.2 on 2025-09-23 06:52

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_usersmodel_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='image',
            field=models.ImageField(blank=True, default='img/user.webp', null=True, upload_to=users.models.convert_file_name),
        ),
    ]
