# Generated by Django 5.1.2 on 2025-09-26 14:28

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_usersmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.convert_file_name),
        ),
    ]
