# Generated by Django 5.1.2 on 2025-09-27 17:29

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_usersmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=users.models.get_default_permissions, null=True),
        ),
    ]
