# Generated by Django 5.1.2 on 2025-09-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_usersmodel_custom_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='display_in_bot',
            field=models.BooleanField(default=True, verbose_name='Показать в боте'),
        ),
    ]
