# Generated by Django 5.1.2 on 2025-05-27 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0039_alter_enrollment_hold'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.IntegerField(blank=True, choices=[(1, 'Нечетные'), (2, 'Четные'), (3, 'Другие')], null=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Ожидание'), (2, 'Обработан'), (3, 'Отменен')], default=1)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel')),
            ],
            options={
                'verbose_name': 'лид',
                'verbose_name_plural': 'лид',
            },
        ),
    ]
