# Generated by Django 5.1.2 on 2025-05-27 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadsmodel',
            options={'verbose_name': 'лид', 'verbose_name_plural': 'лиды'},
        ),
        migrations.AddField(
            model_name='leadsmodel',
            name='lesson_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время урока'),
        ),
        migrations.AddField(
            model_name='leadsmodel',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='учитель'),
        ),
    ]
