# Generated by Django 5.1.2 on 2025-05-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_leadsmodel_options_leadsmodel_lesson_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsmodel',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
