# Generated by Django 5.1.2 on 2025-05-28 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_alter_coursemodel_archived'),
        ('leads', '0006_leadsmodel_active_leadsmodel_enrollment_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsmodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subjectmodel'),
        ),
    ]
