# Generated by Django 5.1.2 on 2025-05-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_leadsmodel_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsmodel',
            name='active',
        ),
        migrations.RemoveField(
            model_name='leadsmodel',
            name='processed',
        ),
    ]
