# Generated by Django 5.1.2 on 2025-05-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_remove_leadsmodel_active_remove_leadsmodel_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsmodel',
            name='processed_date',
        ),
    ]
