# Generated by Django 5.1.2 on 2024-10-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('additional_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('balance', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
