# Generated by Django 5.1.2 on 2024-11-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_enrollment_options_alter_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='trial_lesson',
            field=models.BooleanField(default=False),
        ),
    ]
