# Generated by Django 5.1.2 on 2024-11-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_sessionsmodel_session_number'),
        ('students', '0003_enrollment_trial_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='email',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='additional_number',
            field=models.CharField(default=998900000000, max_length=15, verbose_name='Номер телефона родителей'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='courses',
            field=models.ManyToManyField(through='students.Enrollment', to='courses.coursemodel', verbose_name='Записанные курсы'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
    ]
