# Generated by Django 5.1.2 on 2024-12-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_studentmodel_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='lessons_attended',
            new_name='hold',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='lessons_paid',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='birth_date',
        ),
    ]
