# Generated by Django 5.1.2 on 2024-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_lessons_attended_enrollment_hold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
