# Generated by Django 5.1.2 on 2024-12-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='hold',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='trial_lesson',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
