# Generated by Django 5.1.2 on 2024-12-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_enrollment_hold_alter_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='trial_lesson',
            field=models.BooleanField(default=True),
        ),
    ]
