# Generated by Django 5.1.2 on 2025-01-01 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_sessionsmodel_cancel_on_holiday_and_more'),
        ('students', '0009_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='hold',
            field=models.IntegerField(default=0, null=True, verbose_name='Заморозка'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус Активности'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='trial_lesson',
            field=models.BooleanField(default=True, verbose_name='Пробный урок'),
        ),
    ]
