# Generated by Django 5.1.2 on 2025-01-01 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_enrollment_balance_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидка %'),
        ),
    ]
