# Generated by Django 5.1.2 on 2025-01-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_enrollment_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Баланс'),
        ),
    ]
