# Generated by Django 5.1.2 on 2025-01-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_enrollment_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='hold',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Заморозка'),
        ),
    ]
