# Generated by Django 5.1.2 on 2025-01-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_enrollment_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
