# Generated by Django 5.1.2 on 2025-01-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_enrollment_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='additional_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона родителей'),
        ),
    ]
