# Generated by Django 5.1.2 on 2025-01-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_studentmodel_additional_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'ordering': ['-id'], 'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
    ]
