# Generated by Django 5.1.2 on 2025-02-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_studentmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='debt_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заметка должника'),
        ),
    ]
