# Generated by Django 5.1.2 on 2025-02-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_enrollment_debt_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='additional_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона 2'),
        ),
    ]
