# Generated by Django 5.1.2 on 2025-03-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_studentmodel_additional_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='additional_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона ученика'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона родителя'),
        ),
    ]
