# Generated by Django 5.1.2 on 2025-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_studentmodel_additional_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='debt_note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заметка для учителя'),
        ),
    ]
