# Generated by Django 5.1.2 on 2025-03-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_enrollment_note_alter_enrollment_debt_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'зачисление', 'verbose_name_plural': 'зачислении'},
        ),
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'ordering': ['-id'], 'verbose_name': 'ученик', 'verbose_name_plural': 'ученики'},
        ),
    ]
