# Generated by Django 5.1.2 on 2025-04-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_enrollment_enrolled_at_enrollment_enrolled_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='balance',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_due',
            field=models.DateField(null=True),
        ),
    ]
