# Generated by Django 5.1.2 on 2025-04-06 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_alter_enrollment_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='payment_due',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 6), null=True, verbose_name='Оплачно до'),
        ),
    ]
