# Generated by Django 5.1.2 on 2025-04-06 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_alter_enrollment_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='payment_due',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Оплачно до'),
        ),
    ]
