# Generated by Django 5.1.2 on 2025-04-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_alter_enrollment_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='payment_due',
            field=models.DateField(blank=True, null=True, verbose_name='Оплачно до'),
        ),
    ]
