# Generated by Django 5.1.2 on 2025-04-19 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_alter_enrollment_payment_due'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': '2'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем записан'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
