# Generated by Django 5.1.2 on 2025-04-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_alter_enrollment_enrolled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата записи'),
        ),
    ]
