# Generated by Django 5.1.2 on 2025-04-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_alter_enrollment_enrolled_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at', 'student__first_name', 'student__last_name'], 'verbose_name': 'зачисление', 'verbose_name_plural': 'зачислении'},
        ),
    ]
