# Generated by Django 5.1.2 on 2025-04-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_subjectmodel_show_separately'),
        ('students', '0033_alter_enrollment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel', verbose_name='Курс'),
        ),
    ]
