# Generated by Django 5.1.2 on 2025-04-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_alter_enrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='trail_used_once',
            field=models.BooleanField(default=False),
        ),
    ]
