# Generated by Django 5.1.2 on 2025-05-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_enrollment_trail_used_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='trail_used_once_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
