# Generated by Django 5.1.2 on 2025-05-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_enrollment_trail_used_once_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
