# Generated by Django 5.1.2 on 2025-05-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0037_enrollment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата записи'),
        ),
    ]
