# Generated by Django 5.1.2 on 2025-05-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0038_alter_enrollment_enrolled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='hold',
            field=models.BooleanField(default=False, verbose_name='Заморозка'),
        ),
    ]
