# Generated by Django 5.1.2 on 2025-05-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_alter_enrollment_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата записи'),
        ),
    ]
