# Generated by Django 5.1.2 on 2025-06-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_alter_enrollment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='transferred_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.enrollment'),
        ),
    ]
