# Generated by Django 5.1.2 on 2025-08-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_enrollment_transferred_enrollment_transferred_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
