# Generated by Django 5.1.2 on 2025-10-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_studentmodel_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='absent_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
