# Generated by Django 5.1.2 on 2025-10-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_enrollment_absent_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='absent_note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заметка на отсутствие'),
        ),
    ]
