# Generated by Django 5.1.2 on 2025-08-30 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.PositiveIntegerField(default=0)),
                ('enrollments', models.PositiveIntegerField(default=0)),
                ('trial_enrollments', models.PositiveIntegerField(default=0)),
                ('payments', models.PositiveIntegerField(default=0)),
                ('payments_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_students', models.PositiveIntegerField(default=0)),
                ('new_enrollments', models.PositiveIntegerField(default=0)),
                ('courses', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics',
                'verbose_name_plural': 'Analytics',
            },
        ),
    ]
