# Generated by Django 5.1.2 on 2025-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsmodel',
            options={'verbose_name': 'Аналитика', 'verbose_name_plural': 'Аналитика'},
        ),
        migrations.AlterField(
            model_name='analyticsmodel',
            name='payments_sum',
            field=models.FloatField(default=0),
        ),
    ]
