# Generated by Django 5.1.2 on 2025-08-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analyticsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsmodel',
            name='courses',
            field=models.PositiveIntegerField(default=0, verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='analyticsmodel',
            name='enrollments',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во Зачислений'),
        ),
        migrations.AlterField(
            model_name='analyticsmodel',
            name='new_enrollments',
            field=models.PositiveIntegerField(default=0, verbose_name='Новые Зачисления'),
        ),
        migrations.AlterField(
            model_name='analyticsmodel',
            name='new_students',
            field=models.PositiveIntegerField(default=0, verbose_name='Новые Студенты'),
        ),
        migrations.AlterField(
            model_name='analyticsmodel',
            name='payments',
            field=models.PositiveIntegerField(default=0, verbose_name='Оплаты'),
        ),
        migrations.AlterField(
            model_name='analyticsmodel',
            name='payments_sum',
            field=models.FloatField(default=0, verbose_name='Сумма оплат'),
        ),
        migrations.AlterField(
            model_name='analyticsmodel',
            name='students',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-ва Студентов'),
        ),
        migrations.AlterField(
            model_name='analyticsmodel',
            name='trial_enrollments',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробники'),
        ),
        migrations.AddIndex(
            model_name='analyticsmodel',
            index=models.Index(fields=['date'], name='analytics_a_date_d90da7_idx'),
        ),
    ]
