# Generated by Django 5.1.2 on 2025-08-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_analyticsmodel_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsmodel',
            name='students',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во Студентов'),
        ),
    ]
