# Generated by Django 5.1.2 on 2025-01-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentmodel_amount_alter_paymentmodel_date_and_more'),
        ('students', '0011_enrollment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус Оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.enrollment', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='lessons_covered',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во покрытых уроков'),
        ),
    ]
