# Generated by Django 5.1.2 on 2025-01-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymentmodel_status_alter_paymentmodel_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='status',
        ),
    ]
