# Generated by Django 5.1.2 on 2025-01-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_paymentmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус Оплаты'),
        ),
    ]
