# Generated by Django 5.1.2 on 2025-01-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_paymentmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.FloatField(null=True, verbose_name='Сумма оплаты'),
        ),
    ]
