# Generated by Django 5.1.2 on 2025-01-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_paymentmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='lessons_covered',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во месяйев'),
        ),
    ]
