# Generated by Django 5.1.2 on 2025-02-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_paymentmodel_lessons_covered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='lessons_covered',
            new_name='months',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='status',
        ),
    ]
