# Generated by Django 5.1.2 on 2025-02-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_rename_lessons_covered_paymentmodel_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='months',
            field=models.PositiveIntegerField(choices=[(1, '1 month'), (2, '2 months'), (3, '3 months'), (6, '6 months'), (12, '12 months')], default=1, verbose_name='Кол-во месяйев'),
        ),
    ]
