# Generated by Django 5.1.2 on 2025-02-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_paymentmodel_amount_alter_paymentmodel_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='months',
            field=models.PositiveIntegerField(choices=[(1, '1 Месяц'), (2, '2 Месяца'), (3, '3 Месяца'), (6, '6 Месяца')], verbose_name='Кол-во месяйев'),
        ),
    ]
