# Generated by Django 5.1.2 on 2025-03-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_paymentmodel_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='payed_due',
            field=models.DateField(blank=True, null=True, verbose_name='Конец абонимента'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='payed_from',
            field=models.DateField(blank=True, null=True, verbose_name='Начало абонимента'),
        ),
    ]
