# Generated by Django 5.1.2 on 2025-04-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_paymentmodel_payed_due_paymentmodel_payed_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='current_balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баланс во время оплаты'),
        ),
    ]
