# Generated by Django 5.1.2 on 2025-04-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_paymentmodel_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='current_balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баланс после оплаты оплаты'),
        ),
    ]
