# Generated by Django 5.1.2 on 2025-04-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_paymentmodel_current_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'verbose_name': 'оплата', 'verbose_name_plural': 'оплаты'},
        ),
    ]
