# Generated by Django 5.1.2 on 2025-04-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_paymentmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='current_balance',
        ),
    ]
