# Generated by Django 5.1.2 on 2025-05-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_remove_paymentmodel_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата и время оплаты'),
        ),
    ]
