# Generated by Django 5.1.2 on 2025-05-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_alter_paymentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время оплаты'),
        ),
    ]
