# Generated by Django 5.1.2 on 2025-05-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_alter_paymentmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='manual_dates',
            field=models.BooleanField(default=False),
        ),
    ]
