# Generated by Django 5.1.2 on 2025-07-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_paymentmodel_manual_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='payed_lessons',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='months',
            field=models.PositiveIntegerField(verbose_name='Кол-во месяйев'),
        ),
    ]
