# Generated by Django 5.1.2 on 2025-07-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_paymentmodel_payed_lessons_alter_paymentmodel_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Наличные'), (2, 'Карта'), (3, 'Онлайн перевод')], default=1),
        ),
    ]
