# Generated by Django 5.1.2 on 2025-07-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_alter_paymentmodel_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Наличные'), (2, 'Карта'), (3, 'Онлайн перевод')], default=1, verbose_name='Тип оплаты'),
        ),
    ]
