# Generated by Django 5.1.2 on 2025-10-11 07:03

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_alter_coursemodel_created_at'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано в'),
        ),
        migrations.AlterField(
            model_name='coursematerials',
            name='file',
            field=models.FileField(upload_to=main.models.course_material_upload_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='coursematerials',
            name='file_name',
            field=models.CharField(max_length=150, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='coursematerials',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subjectmodel', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='coursematerials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено в'),
        ),
    ]
