# Generated by Django 5.1.2 on 2024-10-28 14:32

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('weekdays', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота')], max_length=11)),
                ('start_date', models.DateField()),
                ('lesson_time', models.TimeField()),
                ('duration', models.PositiveIntegerField()),
                ('total_lessons', models.PositiveIntegerField()),
                ('course_cost', models.PositiveIntegerField(default=0)),
                ('is_started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subjectmodel')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='SessionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('is_canceled', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'ordering': ['date'],
                'unique_together': {('course', 'session_number')},
            },
        ),
    ]
