# Generated by Django 5.1.2 on 2024-10-25 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('lesson_time', models.TimeField()),
                ('duration', models.TimeField()),
                ('dedicated_lessons', models.PositiveIntegerField()),
                ('is_started', models.BooleanField(default=False)),
                ('students', models.ManyToManyField(to='students.studentmodel')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseSessionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('is_canceled', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('course', 'session_number')},
            },
        ),
    ]
