# Generated by Django 5.1.2 on 2024-10-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSessionsModel',
            new_name='SessionsModel',
        ),
    ]
