# Generated by Django 5.1.2 on 2024-11-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
