# Generated by Django 5.1.2 on 2024-10-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_coursesessionsmodel_sessionsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionsmodel',
            options={'ordering': ['date'], 'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
        migrations.RenameField(
            model_name='coursemodel',
            old_name='dedicated_lessons',
            new_name='total_lessons',
        ),
    ]
