# Generated by Django 5.1.2 on 2024-11-07 14:52

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursemodel_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота')], max_length=11),
        ),
    ]
