# Generated by Django 5.1.2 on 2024-10-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_sessionsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='course_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
