# Generated by Django 5.1.2 on 2024-11-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursemodel_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsmodel',
            name='conducted',
            field=models.BooleanField(default=False),
        ),
    ]
