# Generated by Django 5.1.2 on 2024-11-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_sessionsmodel_conducted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionsmodel',
            name='session_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
