# Generated by Django 5.1.2 on 2024-11-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_sessionsmodel_session_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionsmodel',
            name='session_number',
            field=models.PositiveIntegerField(),
        ),
    ]
