# Generated by Django 5.1.2 on 2024-12-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_sessionsmodel_session_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'ordering': ['id'], 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='sessionsmodel',
            options={'ordering': ['course__id'], 'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
    ]
