# Generated by Django 5.1.2 on 2024-12-17 17:11

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_coursemodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='course_cost',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='session_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='цена урока'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='имя курса'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='продолжительность урока (мин)'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='курс не закончен'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='is_started',
            field=models.BooleanField(default=False, verbose_name='курс начался'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='lesson_time',
            field=models.TimeField(verbose_name='время урока'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='start_date',
            field=models.DateField(verbose_name='начало курса/группы'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subjectmodel', verbose_name='предмет'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='учитель'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='total_lessons',
            field=models.PositiveIntegerField(verbose_name='кл-во уроков'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота')], max_length=11, verbose_name='дни недели'),
        ),
    ]
