# Generated by Django 5.1.2 on 2024-12-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_coursemodel_course_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='курс закончен'),
        ),
    ]
