# Generated by Django 5.1.2 on 2024-12-17 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_coursemodel_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='total_lessons',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='кол-во уроков'),
        ),
    ]
