# Generated by Django 5.1.2 on 2024-12-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_coursemodel_total_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='is_started',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='total_lessons',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус курса'),
        ),
    ]
