# Generated by Django 5.1.2 on 2024-12-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_coursemodel_finished_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionsmodel',
            old_name='conducted',
            new_name='status',
        ),
        migrations.AlterUniqueTogether(
            name='sessionsmodel',
            unique_together={('course', 'date')},
        ),
        migrations.RemoveField(
            model_name='sessionsmodel',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='sessionsmodel',
            name='session_number',
        ),
    ]
