# Generated by Django 5.1.2 on 2024-12-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_sessionsmodel_record_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsmodel',
            name='cancel_fault',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionsmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
