# Generated by Django 5.1.2 on 2024-12-31 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_sessionsmodel_cancel_fault_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionsmodel',
            old_name='cancel_fault',
            new_name='cancel_on_holiday',
        ),
    ]
