# Generated by Django 5.1.2 on 2025-01-01 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_rename_cancel_fault_sessionsmodel_cancel_on_holiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionsmodel',
            name='cancel_on_holiday',
            field=models.BooleanField(null=True, verbose_name='Отменен из-за праздника'),
        ),
        migrations.AlterField(
            model_name='sessionsmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='sessionsmodel',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='sessionsmodel',
            name='record_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем Отмечено'),
        ),
        migrations.AlterField(
            model_name='sessionsmodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус проведение урока'),
        ),
    ]
