# Generated by Django 5.1.2 on 2025-01-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_sessionsmodel_cancel_on_holiday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='session_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена урока'),
        ),
    ]
