# Generated by Django 5.1.2 on 2025-01-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_coursemodel_session_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='session_cost',
            field=models.FloatField(default=0, verbose_name='цена урока'),
        ),
    ]
