# Generated by Django 5.1.2 on 2025-01-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_coursemodel_session_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsmodel',
            name='cause',
            field=models.CharField(choices=[('1', 'Праздник'), ('2', 'Вина Учебного центра')], max_length=50, null=True),
        ),
    ]
