# Generated by Django 5.1.2 on 2025-01-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_sessionsmodel_cause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionsmodel',
            name='cancel_on_holiday',
        ),
    ]
