# Generated by Django 5.1.2 on 2025-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_sessionsmodel_cancel_on_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='session_cost',
            field=models.IntegerField(verbose_name='цена курса за 12 уроков'),
        ),
    ]
