# Generated by Django 5.1.2 on 2025-01-14 10:56

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_coursemodel_session_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], max_length=13, verbose_name='дни недели'),
        ),
    ]
