# Generated by Django 5.1.2 on 2025-01-16 20:45

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_coursemodel_session_cost'),
        ('students', '0014_alter_enrollment_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='enrolled',
            field=models.ManyToManyField(editable=False, through='students.Enrollment', to='students.studentmodel'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='weekdays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], max_length=13, verbose_name='дни недели'),
        ),
    ]
