# Generated by Django 5.1.2 on 2025-01-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_coursemodel_weekdays'),
        ('courses', '0022_coursemodel_enrolled_alter_coursemodel_weekdays'),
    ]

    operations = [
    ]
