# Generated by Django 5.1.2 on 2025-01-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_merge_20250116_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsmodel',
            name='topic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
