# Generated by Django 5.1.2 on 2025-01-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_sessionsmodel_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionsmodel',
            name='topic',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тема'),
        ),
    ]
