# Generated by Django 5.1.2 on 2025-01-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_sessionsmodel_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionsmodel',
            name='cause',
            field=models.CharField(blank=True, choices=[('1', 'Праздник'), ('2', 'Вина Учебного центра')], max_length=50, null=True),
        ),
    ]
