# Generated by Django 5.1.2 on 2025-02-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_sessionsmodel_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='длительность урока (мин)'),
        ),
    ]
