# Generated by Django 5.1.2 on 2025-02-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_coursemodel_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionsmodel',
            options={'ordering': ['-id'], 'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
    ]
