# Generated by Django 5.1.2 on 2025-03-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_sessionsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='last_topic',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тема'),
        ),
    ]
