# Generated by Django 5.1.2 on 2025-03-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_coursemodel_last_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'ordering': ['id'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='sessionsmodel',
            options={'ordering': ['-id'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
