# Generated by Django 5.1.2 on 2025-03-27 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_coursemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'ordering': ['id'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
