# Generated by Django 5.1.2 on 2025-03-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_coursemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionsmodel',
            options={'ordering': ['-id'], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
    ]
