# Generated by Django 5.1.2 on 2025-04-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_sessionsmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'ordering': ['id'], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
    ]
