# Generated by Django 5.1.2 on 2025-04-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_coursemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'ordering': ['weekdays', 'lesson_time'], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='subjectmodel',
            options={'verbose_name': 'предмет', 'verbose_name_plural': 'предметы'},
        ),
    ]
