# Generated by Django 5.1.2 on 2025-04-21 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_coursemodel_options_alter_subjectmodel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'role': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='учитель'),
        ),
    ]
