# Generated by Django 5.1.2 on 2025-04-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_alter_coursemodel_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='show_separately',
            field=models.BooleanField(default=False),
        ),
    ]
