# Generated by Django 5.1.2 on 2025-04-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_subjectmodel_show_separately'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='show_separately',
            field=models.BooleanField(default=False, verbose_name='Отображать раздельно'),
        ),
    ]
