# Generated by Django 5.1.2 on 2025-04-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_subjectmodel_show_separately'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
