# Generated by Django 5.1.2 on 2025-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_coursemodel_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
