# Generated by Django 5.1.2 on 2025-06-10 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_alter_coursemodel_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
