# Generated by Django 5.1.2 on 2025-06-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_coursemodel_created_at_coursemodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
