# Generated by Django 5.1.2 on 2025-06-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_alter_coursemodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='updated_at',
        ),
    ]
