# Generated by Django 5.1.2 on 2025-06-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_alter_subjectmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя предмета'),
        ),
    ]
