# Generated by Django 5.1.2 on 2025-06-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_alter_subjectmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='created_at',
        ),
    ]
