# Generated by Django 5.1.2 on 2025-06-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_coursemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='individual',
            field=models.BooleanField(default=False),
        ),
    ]
