# Generated by Django 5.1.2 on 2025-06-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_subjectmodel_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='individual',
            field=models.BooleanField(default=False, verbose_name='Индивидуальный'),
        ),
    ]
