# Generated by Django 5.1.2 on 2025-09-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_alter_subjectmodel_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата запуска'),
        ),
    ]
