# Generated by Django 5.1.2 on 2025-09-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_coursemodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано в'),
        ),
    ]
