# Generated by Django 5.1.2 on 2024-10-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0003_alter_sessionsmodel_options_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='AttendanceModel',
        ),
    ]
