# Generated by Django 5.1.2 on 2024-11-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0002_alter_coursemodel_course_name'),
        ('students', '0002_alter_enrollment_options_alter_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.CharField(choices=[('1', 'Присутствует'), ('0', 'Отсутствует'), ('3', 'Опоздал')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendancemodel',
            unique_together={('enrollment', 'session')},
        ),
    ]
