# Generated by Django 5.1.2 on 2024-11-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancemodel_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodel',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
