# Generated by Django 5.1.2 on 2024-10-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_attendance_attendancemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancemodel',
            options={'ordering': ['session__date'], 'verbose_name': 'attendance record', 'verbose_name_plural': 'attendance records'},
        ),
    ]
