# Generated by Django 5.1.2 on 2024-12-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendancemodel_remarks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancemodel',
            options={'ordering': ['-id'], 'verbose_name': 'attendance record', 'verbose_name_plural': 'attendance records'},
        ),
    ]
