# Generated by Django 5.1.2 on 2024-12-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='homework_grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='participation_grade',
            field=models.IntegerField(default=0),
        ),
    ]
