# Generated by Django 5.1.2 on 2024-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancemodel_homework_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
