# Generated by Django 5.1.2 on 2024-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendancemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='homework_grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='participation_grade',
            field=models.IntegerField(null=True),
        ),
    ]
