# Generated by Django 5.1.2 on 2025-03-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendancemodel_homework_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancemodel',
            options={'ordering': ['-enrollment__trial_lesson', 'enrollment__student__first_name', 'enrollment__student__last_name'], 'verbose_name': 'attendance record', 'verbose_name_plural': 'attendance records'},
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='trial_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
