# Generated by Django 5.1.2 on 2025-03-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendancemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancemodel',
            options={'ordering': ['-enrollment__trial_lesson', '-trial_attendance', 'enrollment__student__first_name', 'enrollment__student__last_name'], 'verbose_name': 'attendance record', 'verbose_name_plural': 'attendance records'},
        ),
    ]
