# Generated by Django 5.1.2 on 2025-04-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendancemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='status_ch',
            field=models.IntegerField(blank=True, choices=[(1, 'Присутствует'), (0, 'Отсутствует'), (3, 'Опоздал')], null=True),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
