# Generated by Django 5.1.2 on 2025-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendancemodel_status_ch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='homework_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='participation_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
