# Generated by Django 5.1.2 on 2025-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_attendancemodel_homework_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='status_ch',
            field=models.IntegerField(choices=[(1, 'Присутствует'), (0, 'Отсутствует'), (3, 'Опоздал')], null=True),
        ),
    ]
