# Generated by Django 5.1.2 on 2025-04-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_attendancemodel_status_ch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='status_ch',
            field=models.IntegerField(choices=[(1, 'Присутствует'), (0, 'Отсутствует'), (2, 'Опоздал')], null=True),
        ),
    ]
