# Generated by Django 5.1.2 on 2025-04-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_alter_attendancemodel_status_ch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodel',
            name='status_ch',
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Присутствует'), (0, 'Отсутствует'), (2, 'Опоздал')], null=True),
        ),
    ]
