# Generated by Django 5.1.2 on 2025-04-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_remove_attendancemodel_status_ch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancemodel',
            options={'ordering': ['-enrollment__trial_lesson', '-trial_attendance', 'enrollment__student__first_name', 'enrollment__student__last_name'], 'verbose_name': 'посещение', 'verbose_name_plural': 'посещении'},
        ),
    ]
