# Generated by Django 5.1.2 on 2025-04-29 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_attendancemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='trail_used_once',
            field=models.BooleanField(default=False),
        ),
    ]
