# Generated by Django 5.1.2 on 2025-04-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_attendancemodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodel',
            name='trail_used_once',
        ),
    ]
