# Generated by Django 5.1.2 on 2025-05-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_remove_attendancemodel_trail_used_once'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Присутствует'), (0, 'Отсутствует'), (2, 'Опоздал'), (3, 'Заморожен')], null=True),
        ),
    ]
