# Generated by Django 5.1.2 on 2025-07-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_attendancemodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancemodel',
            options={'ordering': ['-enrollment__trial_lesson', '-trial_attendance', 'enrollment__trail_used_once', 'enrollment__student__first_name', 'enrollment__student__last_name'], 'verbose_name': 'посещение', 'verbose_name_plural': 'посещении'},
        ),
    ]
