# Generated by Django 5.1.2 on 2025-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_alter_attendancemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='absent_trial',
            field=models.BooleanField(default=False),
        ),
    ]
