# Generated by Django 5.1.2 on 2025-10-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_attendancemodel_absent_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='absent_trial',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
